apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels: 
        app: web
    spec:
      containers:
        - name: web
          image: timattos/conversao-temperatura:v2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort
